#!/bin/sh

if command -v aplay >/dev/null 2>&1; then
    exec aplay "$@" >/dev/null 2>&1
elif command -v afplay >/dev/null 2>&1; then
    exec afplay "$@" >/dev/null 2>&1
elif command -v play >/dev/null 2>&1; then
    exec play "$@" >/dev/null 2>&1
elif command -v mplayer >/dev/null 2>&1; then
    exec mplayer -nogui -nocache "$@" >/dev/null 2>&1
else
    echo "Can't find an audio player." >&2
    echo "Install aplay, play, afplay or mplayer to enable sound." >&2
    exit 1
fi
